### ISSUE TITLE
error messages got when compiling

### ISSUE THREAD

**Issue by yafangshih** [bharath272/caffe-sds#1]
I was compiling the code. When I `make all` in **caffe-sds** directory, I got the following error messages

```
NVCC src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu

/usr/local/include/google/protobuf/arena.h:909:38: error: conflicting declaration ‘const google::protobuf::internal::integral_constant<bool, ((sizeof (DestructorSkippable<const T>(static_cast<const T*>(0))) == sizeof (char)) || (google::protobuf::internal::has_trivial_destructor<A>::value == true))> google::protobuf::Arena::is_destructor_skippable<T>::value’
     Arena::is_destructor_skippable<T>::value =
                                      ^
/usr/local/include/google/protobuf/arena.h:589:19: error: ‘google::protobuf::Arena::is_destructor_skippable<T>::value’ has a previous declaration as ‘const type google::protobuf::Arena::is_destructor_skippable<T>::value’
     static const type value;
                   ^
/usr/local/include/google/protobuf/arena.h:909:38: error: declaration of ‘const type google::protobuf::Arena::is_destructor_skippable<T>::value’ outside of class is not definition [-fpermissive]
     Arena::is_destructor_skippable<T>::value =
                                      ^
make: *** [.build_release/cuda/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o] Error 1
```

I know it's probably caused by protobuf, 
but I wonder if anyone has encountered similar problems before and how to fix it.

Thanks a lot!

**Comment by bharath272** [comment]
It does seem to be something to do with protobuf, though I don't know what. 
Could you try making the [main caffe repo](https://github.com/BVLC/caffe) and see if you still get the error? If yes, then the caffe-users group might be a good place to ask about this.

Otherwise one will have to figure out what difference is causing this...

**Comment by yafangshih** [comment]
I reported this issue to [google/protobuf](https://github.com/google/protobuf), and turns out it's caused by a bug in NVCC 7.0 as reported in [this issue](https://github.com/google/protobuf/issues/787).
The error occurs when using **cuda7.0**+**Protocol Buffers v3.0.0-beta-1**.
I tried [the patch](https://github.com/google/protobuf/issues/787) provided by Yangqing and it works.

**Comment by yafangshih** [comment]
Would you mind tell which versions of [cuda](https://developer.nvidia.com/cuda-toolkit) and [protobuf](https://github.com/google/protobuf/releases) you used so that maybe I can use the same versions as you to avoid other possible problems in the future.
Thanks again.

**Comment by Yangqing** [comment]
Late to the party, but https://github.com/google/protobuf/pull/1025 would be related. You can also switch back to protobuf 2.6.1 who does not have the problem of arena support. Caffe should work with protobuf 2.
